### ISSUE TITLE
File not sorted

### ISSUE THREAD

**Issue by tiagoapimenta** [qualified/challenge-data#1]
The file [words_alpha.txt](https://github.com/qualified/challenge-data/blob/master/words_alpha.txt) should be sorted. Please, fix it.

**Comment by ggorlen** [comment]
Thanks for reporting, sorry to miss this and apologies for the inaccuracy and any problems this might have caused. I haven't been watching the repo fully until now, unfortunately, but commit [#28db1a0](https://github.com/qualified/challenge-data/commit/28db1a085f5efc3f4fb07972efa2f81a1962cd6c) fixed the issue last year so I'll close it and remove some of the language from the original post.

This issue was inherited from https://github.com/dwyl/english-words. Lesson learned: 8k stars doesn't mean there aren't serious flaws.
